Axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='axf'))
]

app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^$',views.home,name='index'),
    url(r'^home/$',views.home,name='home'),
    url(r'^market/$', views.market, name='market'),

    url(r'^cart/$',views.cart,name='cart'),
    url(r'^mine/$',views.mine,name='mine'),
]

app/models.py
from django.db import models


# insert into axf_wheel(img,name,trackid) values("http://img01.bqstatic.com//upload/activity/2017031716035274.jpg@90Q.jpg","酸奶女王","21870"),("http://img01.bqstatic.com//upload/activity/2017031710450787.jpg@90Q.jpg","优选圣女果","21869"),("http://img01.bqstatic.com//upload/activity/2017030714522982.jpg@90Q.jpg","伊利酸奶大放价","21862"),("http://img01.bqstatic.com//upload/activity/2017032116081698.jpg@90Q.jpg","鲜货直供－窝夫小子","21770"),("http://img01.bqstatic.com//upload/activity/2017032117283348.jpg@90Q.jpg","鲜货直供－狼博森食品","21874");

# 基础类
class Base(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=8)

    class Meta:
        abstract = True


# 轮播图 模型类
class Wheel(Base):
    class Meta:
        db_table = 'axf_wheel'


class Nav(Base):
    class Meta:
        db_table = 'axf_nav'


class Mustbuy(Base):
    class Meta:
        db_table = 'axf_mustbuy'


class Shop(Base):
    class Meta:
        db_table = 'axf_shop'


# 商品
class MainShow(models.Model):
    trackid = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=20)
    brandname = models.CharField(max_length=100)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=20)
    productid1 = models.CharField(max_length=20)
    longname1 = models.CharField(max_length=100)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=20)
    productid2 = models.CharField(max_length=20)
    longname2 = models.CharField(max_length=100)
    price2 = models.CharField(max_length=10)
    marketprice2 = models.CharField(max_length=10)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=20)
    productid3 = models.CharField(max_length=20)
    longname3 = models.CharField(max_length=100)
    price3 = models.CharField(max_length=10)
    marketprice3 = models.CharField(max_length=10)

    class Meta:
        db_table = 'axf_mainshow'


class Foodtypes(models.Model):
    # 分类id
    typeid = models.CharField(max_length=10)
    # 分类名称
    typename = models.CharField(max_length=100)
    # 子类名称
    childtypenames = models.CharField(max_length=200)
    # 分类排序(显示的先后顺序)
    typesort = models.IntegerField()

    class Meta:
        db_table = 'axf_foodtypes'

    def __str__(self):
        return self.typename


class Goods(models.Model):
    # 商品ID
    productid = models.CharField(max_length=10)
    # 商品图片
    productimg = models.CharField(max_length=200)
    # 商品名称
    productname = models.CharField(max_length=100)
    # 商品长名字
    productlongname = models.CharField(max_length=200)
    # 精选
    isxf = models.BooleanField(default=False)
    # 买一送一
    pmdesc = models.BooleanField(default=False)
    # 规格
    specifics = models.CharField(max_length=100)
    # 价格
    price = models.FloatField()
    # 超市价格
    marketprice = models.FloatField()
    # 分类ID
    categoryid = models.CharField(max_length=10)
    # 子类ID
    childcid = models.CharField(max_length=10)
    # 子类名字
    childcidname = models.CharField(max_length=50)
    # 详情id
    dealerid = models.CharField(max_length=10)
    # 库存量
    storenums = models.IntegerField()
    # 销售量
    productnum = models.IntegerField()

    class Meta:
        db_table = 'axf_goods'

app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from app.models import Wheel, Nav, Mustbuy, Shop, MainShow, Foodtypes, Goods


def home(request):
    wheels=Wheel.objects.all()

    navs=Nav.objects.all()

    mustbuys=Mustbuy.objects.all()

    shops =Shop.objects.all()
    shophead=shops[0]
    shoptabs=shops[1:3]
    shopclass=shops[3:7]
    shopcommend=shops[7:11]
    mainShows=MainShow.objects.all()

    return render(request, 'home/home.html',
                  context={"wheels":wheels,
                           "navs":navs,
                           "mustbuys":mustbuys,
                           "shophead":shophead,
                           "shoptabs":shoptabs,
                           "shopclass":shopclass,
                           "shopcommend":shopcommend,
                           "mainShows":mainShows
                           })

def market(request):
    foodtypes=Foodtypes.objects.all()
    #没有时，默认为0
    typeIndex=int(request.COOKIES.get('typeIndex',0))
    categoryid =foodtypes[typeIndex].typeid

    # goodslist=Goods.objects.all()[0:10]
    goodslist = Goods.objects.filter(categoryid=categoryid)
    data={"foodtypes":foodtypes,
          "goodslist":goodslist,
          }
    return render(request, 'market/market.html' ,context=data)


def cart(request):
    return render(request, 'cart/cart.html')


def mine(request):
    return render(request, 'mine/mine.html')


def marketbase(request):
    return redirect('axf:market', 104749)

templates/base/base.html
{% extends 'base/base_template.html' %}
{% load static %}

{% block extbasecss %}
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {% block extcss %}
    {% endblock %}
{% endblock %}

{% block extbasejs %}
    <script src="{% static 'base/js/base.js' %}"></script>
    {% block extjs %}
    {% endblock %}
{% endblock %}

{% block body %}

    {#    头部#}
    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}

    {#    主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

    {#    底部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <dl>
                    <dt><span></span></dt>
                    <dd> 首页 </dd>
                </dl>
            </a>
            <a href="{% url 'axf:market'%}" class="market">
                <dl>
                    <dt><span></span></dt>
                    <dd> 闪购超市 </dd>
                </dl>
            </a>
            <a href="{% url 'axf:cart' %}" class="cart">
                <dl>
                    <dt><span></span></dt>
                    <dd> 购物车 </dd>
                </dl>
            </a>
            <a href="{% url 'axf:mine' %}" class="mine">
                <dl>
                    <dt><span></span></dt>
                    <dd> 我的 </dd>
                </dl>
            </a>
        </footer>
    {% endblock %}
{% endblock %}

templates/base/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    {% block extbasecss %}
    {% endblock %}
</head>
<body>

{% block body %}

{% endblock %}


<script src="{% static 'base/js/jquery.min.js' %}"> </script>
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>
<script src="{% static 'base/js/base_template.js' %}"></script>
{% block extbasejs %}
{% endblock %}

</body>
</html>

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    购物车
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

{% block content %}
    购物车
{% endblock %}

templates/home/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 首页
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/swiper.min.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'home/js/swiper.min.js' %}"></script>
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="home">
        {# 顶部轮播#}
        <div class="swiper-container" id="top-swiper">
            <div class="swiper-wrapper">

                {% for wheel in wheels %}
                    <div class="swiper-slide">
                        <img src="{{ wheel.img }}" alt="">
                    </div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
            <!-- Add Arrows -->
            {#            <div class="swiper-button-next"></div>#}
            {#            <div class="swiper-button-prev"></div>#}
        </div>
        {#导航#}
        <div class="nav">
            <ul>
                {% for nav in navs %}
                    <li>
                        <img src="{{ nav.img }}" alt="">
                        <span>{{ nav.name }}</span>
                    </li>
                {% endfor %}

            </ul>
        </div>
        {#每日必买轮播#}
        <div class="swiper-container" id="mustbuySwiper">
            <div class="swiper-wrapper">

                {% for mustbuy in mustbuys %}
                    <div class="swiper-slide">
                        <img src="{{ mustbuy.img }}" alt="">
                    </div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            {#            <div class="swiper-pagination"></div>#}
            <!-- Add Arrows -->
            {#            <div class="swiper-button-next"></div>#}
            {#            <div class="swiper-button-prev"></div>#}
        </div>

        <div class="shop">
            <div class="shophead">
                <img src="{{ shophead.img }}" alt="">
            </div>
            
            <div class="shoptab">
                {% for shoptab in shoptabs %}
                    <a href="#">
                        <img src="{{ shoptab.img }}" alt="">
                    </a>
                {% endfor %}
                
            </div>
            
            <ul class="shopclass">
                {% for item in shopclass %}
                    <li>
                        <a href="">
                            <img src="{{ item.img }}" alt="">
                        </a>
                    </li>
                {% endfor %}
                
            </ul>
            
            <ul class="shopcommend">
                {% for item in shopcommend %}
                    <li>
                        <a href="#">
                            <img src="{{ item.img }}" alt="">
                        </a>
                    </li>
                {% endfor %}
                
            </ul>
        </div>

{#商品主体#}
        <div class="main">
            {% for mainShow in mainShows %}
                <div class="main-wrapper">
                    <div class="title">
                        {{ mainShow.name }}
                        <a href="#"> 更多 </a>
                        <span></span>
                    </div>

                    <div class="headimg">
                        <img src="{{ mainShow.img }}" alt="">
                    </div>

                    <div class="shoplist">
                        <div class="shopitem">
                            <img  class="img" src="{{ mainShow.img1 }}" alt="">

                            <span class="desc">{{ mainShow.longname1 }}</span>

                            <span class="price">{{ mainShow.price1 }}</span>

                            <span class="marketprice">{{ mainShow.marketprice1 }}</span>

                            <button><span>+</span></button>
                        </div>

                        <div class="shopitem">
                            <img  class="img" src="{{ mainShow.img2 }}" alt="">

                            <span class="desc">{{ mainShow.longname2 }}</span>

                            <span class="price">{{ mainShow.price2 }}</span>

                            <span class="marketprice">{{ mainShow.marketprice2 }}</span>

                            <button><span>+</span></button>
                        </div>

                        <div class="shopitem">
                            <img  class="img" src="{{ mainShow.img3 }}" alt="">

                            <span class="desc">{{ mainShow.longname3 }}</span>

                            <span class="price">{{ mainShow.price3 }}</span>

                            <span class="marketprice">{{ mainShow.marketprice3 }}</span>

                            <button><span>+</span></button>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    闪购超市
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'market/js/jquery.cookie.js' %}"></script>
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="market">
        {#        侧边栏#}
        {#        侧边栏(分类)#}
        <div class="type-slider">
            <ul>
                {% for foodtype in foodtypes %}
                    <li class="type-item">
                        <span></span>
                        <a href="{% url 'axf:market'  %}">
                            {{ foodtype.typename }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

{#        导航(分类、排序)#}
        <nav>
            <ul>
                <li>
                    <span>
                        全部类型
                        <i class="glyphicon glyphicon-arrow-up"></i>
                    </span>
                </li>
                <li>
                    <span>
                        综合排序
                        <i class="glyphicon glyphicon-arrow-up"></i>
                    </span>
                </li>
            </ul>
        </nav>

{#        商品列表#}
        <div class="main-content">
            <div class="content-wrapper">
                <ul>
                    {% for goods in goodslist %}
{#                        一个个商品#}
                        <li>
                            <a href="#">
                                <img class="goods-img" src="{{ goods.productimg }}" alt="">
                                <div class="goods-info">
                                    <p class="name">
                                        {{ goods.productlongname }}
                                    </p>
                                    <p class="detailtag">
                                        {% if goods.isxf %}
                                            <span class="xf">精选</span>
                                        {% endif %}
                                    </p>
                                    <p class="specifics">
                                        {{ goods.specifics }}
                                    </p>
                                    <p class="price">
                                        <span class="now-price"> ￥{{ goods.price }} </span>
                                        <span class="market-price">
                                            ￥{{ goods.marketprice }}
                                        </span>
                                    </p>
                                </div>
                            </a>
                            <div class="bt-wrapper">
                                <span class="glyphicon glyphicon-minus"></span>
                                <span class="num">10</span>
                                <span class="glyphicon glyphicon-plus"></span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    我的
{% endblock %}